# This file extends the docker-compose.yml with production configurations/overrides. https://docs.docker.com/compose/compose-file/13-merge/
version: "3.8"
services:
  restic:
    # Add a name to easy identify
    container_name: resticProd
